<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>FrameworksDrivers_API</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="11.11.0" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.8" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ApplicationLayer-UC\ApplicationLayer-UC.csproj" />
    <ProjectReference Include="..\EnterpriseLayer\EnterpriseLayer.csproj" />
    <ProjectReference Include="..\FrameworksDrivers-ExternalService\FrameworksDrivers-ExternalService.csproj" />
    <ProjectReference Include="..\InterfaceAdapters-Adapters\InterfaceAdapters-Adapters.csproj" />
    <ProjectReference Include="..\InterfaceAdapters-Data\InterfaceAdapters-Data.csproj" />
    <ProjectReference Include="..\InterfaceAdapters-Mappers\InterfaceAdapters-Mappers.csproj" />
    <ProjectReference Include="..\InterfaceAdapters-Models\InterfaceAdapters-Models.csproj" />
    <ProjectReference Include="..\InterfaceAdapters-Presenters\InterfaceAdapters-Presenters.csproj" />
    <ProjectReference Include="..\InterfaceAdapters-Repository\InterfaceAdapters-Repository.csproj" />
  </ItemGroup>

</Project>
