<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>InterfaceAdapters_Adapters</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ApplicationLayer-UC\ApplicationLayer-UC.csproj" />
    <ProjectReference Include="..\EnterpriseLayer\EnterpriseLayer.csproj" />
  </ItemGroup>

</Project>
